---
title: "Day 18"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)

options(scipen = 999)
```

## Challenge 1

1 + (2 * 3) + (4 * (5 + 6))

(1) %>% (add((2) %>% mult(3)) %>% add((4) %>% mult((5) %>% add(6)))

+ becomes ") %>% add("
* becomes ") %>% mult("
parenthesis beginning and end

```{r}
library(dplyr)
library(stringr)
library(readr)
library(tibble)
library(purrr)

add <- function(x, y){x + y}
mult <- function(x, y){x * y}

eval_string <- function(str){
  return(str %>% str_replace_all("\\+", ") %>% add(") %>% 
    str_replace_all("\\*", ") %>% mult(") %>% 
    paste0("(", ., ")") %>% 
    parse(text = .) %>% 
    eval())
}

input <- read_lines(here::here("data/input_18.txt")) 

input %>% 
  map_dbl(eval_string) %>% 
  sum()
```

## Challenge 2

We define "special plus" as an infix operator, giving it higher precedence than multiplication.

```{r}
`%add%` <- function(x, y){x + y}

eval_string_p2 <- function(str){
  return(str %>% str_replace_all("\\+", "%add%") %>% 
    parse(text = .) %>% 
    eval())
}

input %>% 
  map_dbl(eval_string_p2) %>% 
  sum()
```

